INFO 07-29 13:49:16 [__init__.py:235] Automatically detected platform cuda.
Using evaluation config: broad=True, zero_shot=True
Using prompt:  broad_0_shot.txt
INFO 07-29 13:49:24 [config.py:1604] Using max model len 32768
INFO 07-29 13:49:24 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/transformers_utils/tokenizer_group.py:24: FutureWarning: It is strongly recommended to run mistral models with `--tokenizer-mode "mistral"` to ensure correct encoding and decoding.
  self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
INFO 07-29 13:49:25 [core.py:572] Waiting for init message from front-end.
INFO 07-29 13:49:25 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='mistralai/Mistral-7B-Instruct-v0.3', speculative_config=None, tokenizer='mistralai/Mistral-7B-Instruct-v0.3', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=mistralai/Mistral-7B-Instruct-v0.3, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
ERROR 07-29 13:49:26 [core.py:632] EngineCore failed to start.
ERROR 07-29 13:49:26 [core.py:632] Traceback (most recent call last):
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 623, in run_engine_core
ERROR 07-29 13:49:26 [core.py:632]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 07-29 13:49:26 [core.py:632]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 441, in __init__
ERROR 07-29 13:49:26 [core.py:632]     super().__init__(vllm_config, executor_class, log_stats,
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 77, in __init__
ERROR 07-29 13:49:26 [core.py:632]     self.model_executor = executor_class(vllm_config)
ERROR 07-29 13:49:26 [core.py:632]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 53, in __init__
ERROR 07-29 13:49:26 [core.py:632]     self._init_executor()
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
ERROR 07-29 13:49:26 [core.py:632]     self.collective_rpc("init_worker", args=([kwargs], ))
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
ERROR 07-29 13:49:26 [core.py:632]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 07-29 13:49:26 [core.py:632]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/utils/__init__.py", line 2985, in run_method
ERROR 07-29 13:49:26 [core.py:632]     return func(*args, **kwargs)
ERROR 07-29 13:49:26 [core.py:632]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 556, in init_worker
ERROR 07-29 13:49:26 [core.py:632]     worker_class = resolve_obj_by_qualname(
ERROR 07-29 13:49:26 [core.py:632]                    ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/utils/__init__.py", line 2539, in resolve_obj_by_qualname
ERROR 07-29 13:49:26 [core.py:632]     module = importlib.import_module(module_name)
ERROR 07-29 13:49:26 [core.py:632]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/importlib/__init__.py", line 126, in import_module
ERROR 07-29 13:49:26 [core.py:632]     return _bootstrap._gcd_import(name[level:], package, level)
ERROR 07-29 13:49:26 [core.py:632]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 07-29 13:49:26 [core.py:632]   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
ERROR 07-29 13:49:26 [core.py:632]   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ERROR 07-29 13:49:26 [core.py:632]   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ERROR 07-29 13:49:26 [core.py:632]   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ERROR 07-29 13:49:26 [core.py:632]   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
ERROR 07-29 13:49:26 [core.py:632]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/worker/gpu_worker.py", line 33, in <module>
ERROR 07-29 13:49:26 [core.py:632]     from vllm.v1.worker.gpu_model_runner import GPUModelRunner
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 67, in <module>
ERROR 07-29 13:49:26 [core.py:632]     from vllm.v1.spec_decode.ngram_proposer import NgramProposer
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/spec_decode/ngram_proposer.py", line 6, in <module>
ERROR 07-29 13:49:26 [core.py:632]     from numba import jit
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/numba/__init__.py", line 59, in <module>
ERROR 07-29 13:49:26 [core.py:632]     _ensure_critical_deps()
ERROR 07-29 13:49:26 [core.py:632]   File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/numba/__init__.py", line 45, in _ensure_critical_deps
ERROR 07-29 13:49:26 [core.py:632]     raise ImportError(msg)
ERROR 07-29 13:49:26 [core.py:632] ImportError: Numba needs NumPy 2.2 or less. Got NumPy 2.3.
Process EngineCore_0:
Traceback (most recent call last):
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 636, in run_engine_core
    raise e
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 623, in run_engine_core
    engine_core = EngineCoreProc(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 441, in __init__
    super().__init__(vllm_config, executor_class, log_stats,
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 77, in __init__
    self.model_executor = executor_class(vllm_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 53, in __init__
    self._init_executor()
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    self.collective_rpc("init_worker", args=([kwargs], ))
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/utils/__init__.py", line 2985, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 556, in init_worker
    worker_class = resolve_obj_by_qualname(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/utils/__init__.py", line 2539, in resolve_obj_by_qualname
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/worker/gpu_worker.py", line 33, in <module>
    from vllm.v1.worker.gpu_model_runner import GPUModelRunner
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 67, in <module>
    from vllm.v1.spec_decode.ngram_proposer import NgramProposer
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/spec_decode/ngram_proposer.py", line 6, in <module>
    from numba import jit
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/numba/__init__.py", line 59, in <module>
    _ensure_critical_deps()
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/numba/__init__.py", line 45, in _ensure_critical_deps
    raise ImportError(msg)
ImportError: Numba needs NumPy 2.2 or less. Got NumPy 2.3.
Traceback (most recent call last):
  File "/home/songk1/Documents/PURM-25/vllm_eval.py", line 181, in <module>
    main()
  File "/home/songk1/Documents/PURM-25/vllm_eval.py", line 166, in main
    llm = load_model(model_id)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/Documents/PURM-25/vllm_eval.py", line 26, in load_model
    llm = LLM(
          ^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 273, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 497, in from_engine_args
    return engine_cls.from_vllm_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 126, in from_vllm_config
    return cls(vllm_config=vllm_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 103, in __init__
    self.engine_core = EngineCoreClient.make_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 77, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 514, in __init__
    super().__init__(
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 408, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 697, in launch_core_engines
    wait_for_engine_startup(
  File "/home/songk1/miniconda3/envs/vllm_env/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 750, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
